question_data = [
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Science: Computers",
     "question": "The HTML5 standard was published in 2014.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "The very first recorded computer 'bug, was a moth found inside a Harvard Mark II computer.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "The 'Raspberry' series of single-board computers were created in the United States.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "There is only 1 root name server, among 13 in total, that is currently located in Asia.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "FLAC stands for 'Free Lossless Audio Condenser'",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Science: Computers",
    "question": "MacOS is based on Linux.",
     "correct_answer": "False",
    "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
     "question": "The open source program Redis is a relational database server.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "medium",
     "category": "Science: Computers",
     "question": "The ARM computer chip was originally developed by Acorn Computers.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     }
]
